
export const ACCESS_TOKEN_UPDATE = "ACCESS_TOKEN_UPDATE";
export type ACCESS_TOKEN_UPDATE = typeof ACCESS_TOKEN_UPDATE;

export const DELIVERIES_LOADED = "DELIVERIES_LOADED";
export type DELIVERIES_LOADED = typeof DELIVERIES_LOADED;

export const ITEM_GROUP_CATEGORY_UPDATE = "ITEM_GROUP_CATEGORY_UPDATE";
export type ITEM_GROUP_CATEGORY_UPDATE = typeof ITEM_GROUP_CATEGORY_UPDATE;