
export const ACCESS_TOKEN_UPDATE = "ACCESS_TOKEN_UPDATE";
export type ACCESS_TOKEN_UPDATE = typeof ACCESS_TOKEN_UPDATE;

export const DELIVERIES_LOADED = "DELIVERIES_LOADED";
export type DELIVERIES_LOADED = typeof DELIVERIES_LOADED;

export const PRODUCTS_LOADED = "PRODUCTS_LOADED";
export type PRODUCTS_LOADED = typeof PRODUCTS_LOADED;